- name: Step 00xxxxx post software
  hosts: support
  gather_facts: False
  become: yes
  tasks:
    - debug:
        msg: "Post-Software tasks Started"

- name: Configure Ansible Tower
  hosts: towers
  gather_facts: False
  become: yes
  tasks:

    - name: Ensure required inventories are added to Tower
      include_role:
        name: infra-ansible/roles/ansible/tower/manage-inventories
    
    - name: Ensure required Projects are added to Tower
      include_role:
        name: infra-ansible/roles/ansible/tower/manage-projects

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
