- name: Step 005 Post Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 005 Post Software"

- name: Step lab post software deployment
  hosts: bastions
  become: yes
  tags:
    - bastion_post_software
  tasks:
    - name: Create control-user
      include_role:
        name: control-user

- name: Deploy user.info
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - step005
  tasks:

    - name: print out user.info
      agnosticd_user_info:
        msg: "{{ item }}"
      loop:
        - "To access bastion via SSH:"
        - "ssh  {{ student_name }}@bastion.{{ guid }}.{{ osp_cluster_dns_zone }}"
        - "Enter ssh password when prompted: {{ hostvars['bastion']['student_password'] }}"

    - name: Save user data
      agnosticd_user_info:
        data:
          ssh_command: "ssh  {{ student_name }}@bastion.{{ guid }}.{{ osp_cluster_dns_zone }}"
          ssh_password: "{{ hostvars['bastion']['student_password'] }}"


- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
